services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: base_db
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  redis:
    image: redis:7.4
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # redis-exporter:
  #   image: oliver006/redis_exporter:latest
  #   container_name: redis-exporter
  #   command:
  #     - --redis.addr=redis://redis:6379
  #   ports:
  #     - "9121:9121"
  #   depends_on:
  #     - redis
  #   networks:
  #     - app-network

  kafka1:
    image: apache/kafka:3.8.0
    container_name: kafka1
    hostname: kafka1
    networks:
      - app-network
    ports:
      - "9092:9092"
    volumes:
      - kafka-data-1:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    restart: unless-stopped

  kafka2:
    image: apache/kafka:3.8.0
    container_name: kafka2
    hostname: kafka2
    networks:
      - app-network
    ports:
      - "9093:9092"
    volumes:
      - kafka-data-2:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    restart: unless-stopped

#  kafka3:
#    image: apache/kafka:3.8.0
#    container_name: kafka3
#    hostname: kafka3
#    networks:
#      - app-network
#    ports:
#      - "9094:9092"
#    volumes:
#      - kafka-data-3:/var/lib/kafka/data
#    environment:
#      KAFKA_NODE_ID: 3
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka3:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9094
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
#    restart: unless-stopped

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - app-network

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - app-network

  # akhq:
  #   image: tchiotludo/akhq:latest
  #   container_name: akhq
  #   hostname: akhq
  #   networks:
  #     - app-network
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     AKHQ_CONFIGURATION: |
  #       akhq:
  #         connections:
  #           docker-kafka-cluster:
  #             properties:
  #               bootstrap.servers: "kafka1:29092,kafka2:29092"
  #   restart: unless-stopped

  spring-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: unless-stopped
    environment:
      FILE_LOCATION: /app/uploads/production
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/base_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JACKSON_TIME_ZONE: Asia/Seoul
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:29092,kafka2:29093
    volumes:
      - /var/app/uploads:/app/uploads/production
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  kafka-data-1:
    driver: local
  kafka-data-2:
    driver: local
#   kafka-data-3:
#     driver: local
